### ISSUE TITLE
.envrc not loaded on initial directory entry when starting up xonsh

### ISSUE THREAD

**Issue by halloleo** [74th/xonsh-direnv#1]
I have `direnv` and `xonsh-direnv` installed, plus I load the  `xonsh-direnv` xontrib  in the `.xonshrc.`

However when I start up xonsh the `.envrc` in the directory xonsh starts in is not loaded. I have manually to change directories  and change back into my directory to load it.

How can  I load the `.envrc` file on xonsh start up?

**Comment by 74th** [comment]
I fixed v1.3.
It loads on xonsh start up. 
Please update xonsh-direnv.

**Comment by con-f-use** [comment]
Not really fixed, because `.envrc` is interpreted in bash. You can't put xonsh commands in there.

Eample:
```
┌─15-17:00 [(python-2.7.15+) confus@confusion6 ~/devel/autotest]                                                                           😱  master|+2…2 😱
└$ echo xonfig >> .envrc
                                                                                                                                       
direnv: error .envrc is blocked. Run `direnv allow` to approve its content.

┌─15-17:02 [confus@confusion6 ~/devel/autotest]                                                                                            😱  master|+2…2 😱
└$ direnv allow ./
                                                                                                                                              
direnv: loading .envrc
source /home/jan/devel/cuda/autotest/autotest-core/bin/bashcomplete_manager.py
completer add manager xonsh_manager_completer '<path'
./.envrc: line 6: xonfig: command not found
direnv: export +VIRTUAL_ENV -PS2 ~PATH

┌─15-17:02 [(python-2.7.15+) confus@confusion6 ~/devel/autotest]                                                                           😱  master|+2…2 😱
└$ vi .envrc
                                                                                                                                                   
direnv: loading .envrc
source /home/jan/devel/cuda/autotest/autotest-core/bin/bashcomplete_manager.py
completer add manager xonsh_manager_completer '<path'
direnv: export +VIRTUAL_ENV -PS2 ~PATH
```

**Comment by 74th** [comment]
I see direnv has only loading or unloading environment variables.
https://github.com/direnv/direnv

**Comment by con-f-use** [comment]
Interesting, then I was fooled by this:

```
┌─16-20:16 [confus@jcgbx ~]                                                  😱  😱
└$ bash                                                                         

┌─16-20:17[confus@jcgbx:~] 130 $ 
└▪ echo layout python3 > .envrc; direnv allow .
direnv: loading .envrc
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/jan/.direnv/python-3.6.8/bin/python3
Also creating executable in /home/jan/.direnv/python-3.6.8/bin/python
Installing setuptools, pip, wheel...
done.
direnv: export +VIRTUAL_ENV -PS2 ~PATH

┌─16-20:17[confus@jcgbx:~] [python-3.6.8] $ 
└▪ echo 'echo Hi and welcome!' >> .envrc; direnv allow .
direnv: loading .envrc
Hi and welcome!
direnv: export +VIRTUAL_ENV -PS2 ~PATH
```

The relevant part on the direnv github page is:

> If the [.envrc] file exists (and is authorized), it is loaded into a **bash sub-shell** and all exported variables are then captured by direnv.

So the bash-part seems to be hardcoded in direnv.
